[general]
fullscreen = true
early-exit = true
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "/home/phrmendes/Pictures/Screenshots/%Y-%m-%d_%H:%M:%S.png"
save-after-copy = false
default-hide-toolbars = false
