[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yy"

[[session]]
name = "documents"
path = "~/Documents"
startup_command = "yy"

[[session]]
name = "dotfiles"
path = "~/Projects/dotfiles"
startup_command = "nvim -c ':Pick files'"

[[session]]
name = "neovim config"
path = "~/Projects/dotfiles/modules"
startup_command = "nvim neovim.nix"
