format = """
$username\
$hostname\
$directory\
($git_branch)\
($git_state)\
($git_status)\
$fill\
($python)\
($cmd_duration)\
$line_break\
($nix_shell)\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[󰘧](bold purple)"
error_symbol = "[󰘧](bold red)"
vimcmd_symbol = "[󰘧](bold green)"

[fill]
symbol = " "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = ' [[(\[$conflicted$untracked$modified$staged$renamed$deleted$stashed\])](218) ($ahead_behind)]($style)'
style = "cyan"
conflicted = "!"
untracked = "?"
modified = "*"
staged = "+"
renamed = "r"
deleted = "x"
stashed = "≡"

[cmd_duration]
format = " [ $duration]($style)"
style = "yellow"

[python]
format = " [ $virtualenv]($style)"
style = "green"

[nix_shell]
format = '[]($style) '
style = "bold blue"

[hostname]
ssh_symbol = " "
