- name: Backup configuration for linux computers running PopOS 22.04
  hosts: localhost

  tasks:
    - name: Remove packages with apt
      become: yes
      ansible.builtin.apt:
        state: absent
        name:
          - evince
          - fprintd
          - geary
          - gnome-calendar
          - gnome-contacts
          - gnome-terminal
          - gparted
          - simple-scan
          - totem
          - xterm

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install packages with flatpak
      community.general.flatpak:
        state: present
        name:
          - ch.protonmail.protonmail-bridge
          - com.github.ransome1.sleek
          - com.github.tchx84.Flatseal
          - com.protonvpn.www
          - org.wezfurlong.wezterm

    - name: Install packages with apt
      become: yes
      ansible.builtin.apt:
        state: present
        name:
          - atool
          - build-essential
          - ca-certificates
          - catdoc
          - curl
          - exiftool
          - file
          - file-roller
          - flatpak
          - fonts-dejavu
          - fonts-jetbrains-mono
          - gdebi-core
          - git
          - gnome-tweaks
          - gnupg
          - gzip
          - jq
          - libbz2-dev
          - libffi-dev
          - libfuse2
          - liblzma-dev
          - libncursesw5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - libxml2-dev
          - libxmlsec1-dev
          - mediainfo
          - mlocate
          - openssh-server
          - rar
          - tailscale
          - tk-dev
          - uidmap
          - unrar
          - unzip
          - w3m
          - wget
          - xclip
          - xlsx2csv
          - xz-utils
          - zip
          - zlib1g-dev
