---
- name: Backup configuration for PopOS 22.04
  become: true
  connection: local
  hosts: localhost

  collections:
    - community.general

  vars_files:
    - ./ansible/variables.yaml

  pre_tasks:
    - name: Fix ansible variable
      ansible.builtin.set_fact:
        ansible_distribution: "{{ 'Ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution }}"

  roles:
    - geerlingguy.docker

  tasks:
    - name: Import tasks
      ansible.builtin.include_tasks:
        file: "{{ file }}"
      loop:
        - ./ansible/tasks/apt.yaml
        - ./ansible/tasks/flatpak.yaml
        - ./ansible/tasks/fingerprint.yaml
        - ./ansible/tasks/nix.yaml
        - ./ansible/tasks/nerd-fonts.yaml
        - ./ansible/tasks/debugpy.yaml
        - ./ansible/tasks/pcloud.yaml
        - ./ansible/tasks/wezterm.yaml
      loop_control:
        loop_var: file
