---
- name: Backup configuration for PopOS 22.04
  become: true
  connection: local
  hosts: localhost
  collections:
    - community.general

  vars_files:
    - ./ansible/variables.yaml

  roles:
    - geerlingguy.docker

  tasks:
    - name: Import tasks
      import_tasks: 
        file: "{{ item }}"
      with_items:   
        - ./ansible/tasks/apt.yaml
        - ./ansible/tasks/flatpak.yaml
        - ./ansible/tasks/fingerprint.yaml
        - ./ansible/tasks/nix.yaml
        - ./ansible/tasks/home-manager.yaml
        - ./ansible/tasks/bin.yaml
        - ./ansible/tasks/nerd-fonts.yaml