---
- name: Backup configuration for PopOS 22.04
  become: true
  connection: local
  hosts: localhost
  collections:
    - community.general

  vars_files:
    - ./ansible/variables.yaml

  pre_tasks:
    - name: Fix ansible variable
      set_fact:
        ansible_distribution: "{{ 'Ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution }}"

  tasks:
    - name: Import tasks
      include_tasks:
        file: "{{ file }}"
      loop:
        - ./ansible/tasks/apt.yaml
        - ./ansible/tasks/flatpak.yaml
        - ./ansible/tasks/fingerprint.yaml
        - ./ansible/tasks/nix.yaml
        - ./ansible/tasks/home-manager.yaml
        - ./ansible/tasks/bin.yaml
        - ./ansible/tasks/nerd-fonts.yaml
        - ./ansible/tasks/desktop_entries.yaml
      loop_control:
        loop_var: file
