---
- name: Backup configuration for PopOS 22.04
  connection: local
  hosts: localhost

  vars_files:
    - ./ansible/variables.yaml

  tasks:
    - name: Import tasks
      ansible.builtin.include_tasks:
        file: "{{ file }}"
      loop:
        - ansible/tasks/apt.yaml
        - ansible/tasks/flatpak.yaml
        - ansible/tasks/nix.yaml
        - ansible/tasks/nerd-fonts.yaml
        - ansible/tasks/debugpy.yaml
        - ansible/tasks/wezterm.yaml
      loop_control:
        loop_var: file
