---
- name: Backup configuration for PopOS 22.04
  become: true
  connection: local
  hosts: localhost

  vars_files:
    - ./ansible/variables.yaml

  pre_tasks:
    - import_tasks: ./ansible/tasks/custom-facts.yaml

  roles:
    - geerlingguy.docker

  tasks:
    - import_tasks: ./ansible/tasks/apt.yaml
    - import_tasks: ./ansible/tasks/flatpak.yaml
    - import_tasks: ./ansible/tasks/fingerprint.yaml
    - import_tasks: ./ansible/tasks/nix.yaml
    - import_tasks: ./ansible/tasks/home-manager.yaml
    - import_tasks: ./ansible/tasks/pyenv.yaml
    - import_tasks: ./ansible/tasks/pcloud.yaml
    - import_tasks: ./ansible/tasks/nerd-font.yaml
