---
- name: Backup configuration for PopOS 22.04
  become: true
  hosts: all
  connection: local

  vars_files:
    - ./ansible/variables.yaml

  pre_tasks:
    - import_tasks: ./ansible/tasks/custom_facts.yaml

  tasks:
    - import_tasks: ./ansible/tasks/apt.yaml
    - import_tasks: ./ansible/tasks/docker.yaml
    - import_tasks: ./ansible/tasks/flatpak.yaml
    - import_tasks: ./ansible/tasks/fingerprint.yaml
    - import_tasks: ./ansible/tasks/nix.yaml
    - import_tasks: ./ansible/tasks/home-manager.yaml
    - import_tasks: ./ansible/tasks/pyenv.yaml
    - import_tasks: ./ansible/tasks/services.yaml
