name: base
channels:
  - defaults
  - bioconda
  - defaults
  - R
dependencies:
  - pip
  - pandas
  - polars
  - matplotlib
  - numpy
  - scipy
  - sympy
  - pyarrow
  - r-base
  - r-tidyverse
  - r-data.table
  - r-quarto
  - r-janitor
  - r-pbapply
  - r-styler
  - r-zoo
  - r-xts
  - r-lintr
  - r-fs
  - r-distill
  - r-arrow
  - r-duckdb
