theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
mouse = true
true-color = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┆"

[editor.soft-wrap]
enable = true

[keys.normal.space]
"\\" = "vsplit"
minus = "hsplit"
q = ":quit"
w = ":write"
x = "wclose"

[keys.normal."]"]
b = "goto_next_buffer"

[keys.normal."["]
b = "goto_previous_buffer"
