theme = "catppuccin_mocha"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
mouse = true
true-color = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner", "diagnostics"]
right = ["file-base-name", "selections", "position", "file-encoding"]

[keys.normal]
"$" = "goto_line_end"
0 = "goto_line_start"
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
"^" = "goto_first_nonwhitespace"
"}" = ["goto_next_paragraph", "collapse_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
S = "surround_add"
V = ["select_mode", "extend_to_line_bounds"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"$" = "goto_line_end"
0 = "goto_line_start"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
G = "goto_file_end"
S = "surround_add"

[keys.normal.y]
g = { g = [
  "select_mode",
  "extend_to_line_bounds",
  "goto_file_start",
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
] }
G = [
  "select_mode",
  "extend_to_line_bounds",
  "goto_last_line",
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
W = [
  "move_next_long_word_start",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
w = [
  "move_next_word_start",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "collapse_selection",
]
