theme = "catppuccin_mocha"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal.space]
Q = ":q"
q = ":bc"
space = "file_picker"
w = ":w"