theme = "catppuccin_mocha"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
Q = ":q"
q = ":bc"
space = "file_picker"
w = ":w"