[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-filename", "$FILENAME"] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = ["-"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = [ "--parser", "json"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [ "--parser", "markdown"] }

[[language]]
name = "hcl"
auto-format = true
formatter = { command = "terraform", args = ["fmt", "-"] }

[[language]]
name = "tfvars"
formatter = { command = "terraform", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }