# TODO: setup DAP
# TODO: setup multiples language servers for markdown and python
# TODO: setup pyright with ruff-lsp and ruff

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]

[language-server.ruff]
command = "ruff-lsp"

[language-server.ltex]
command = "ltex-ls"

[[language]]
name = "python"
auto-format = true
roots = ["pyproject.toml", "poetry.lock"]

[[python.config.pylsp.plugins]]
ruff.enable = true
rope.enable = true
mypy = { enable = true, strict = true }

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = [ "-i", "4"] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = [ "--parser", "yaml" ] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = [ "--parser", "json" ] }

[[language]]
name = "markdown"
auto-format = true
# language-servers = ["marksman", "ltex"]
formatter = { command = "prettier", args = [ "--parser", "markdown"] }

[[language]]
name = "html"
formatter = { command = 'prettier', args = [ "--parser", "html" ] }

[[language]]
name = "hcl"
auto-format = true
formatter = { command = "terraform", args = [ "fmt", "-" ] }

[[language]]
name = "tfvars"
auto-format = true
formatter = { command = "terraform", args = [ "fmt", "-" ] }