use_trash = true
watch_files = true
xdg_open = false
xdg_open_fork = false

[display]
mode = "default"

automatically_count_files = false
collapse_preview = true
column_ratio = [1, 4, 4]
scroll_offset = 6
show_borders = true
show_hidden = false
show_icons = true
line_number_style = "none"
linemode = "size"

[display.sort]
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 2097152
preview_script = "~/.local/bin/joshuto_preview.sh"

[search]
string_case_sensitivity = "insensitive"
glob_case_sensitivity = "sensitive"
regex_case_sensitivity = "sensitive"
fzf_case_sensitivity = "insensitive"

[tab]
home_page = "home"

[cmd_aliases]
q = "quit --output-current-directory"
