[class]
audio_default = [
  { command = "vlc", args = [
    "--",
  ], fork = true, silent = true },
  { command = "mediainfo", confirm_exit = true },
]

video_default = [
  { command = "vlc", args = [
    "--",
  ], fork = true, silent = true },
  { command = "mediainfo", confirm_exit = true },
]

image_default = [
  { command = "qview", args = [
    "--",
  ], fork = true, silent = true },
]

text_default = [
  { command = "hx" },
  { command = "code" },
  { command = "bat", args = [
    "--paging=always",
  ] },
]

reader_default = [{ command = "evince", fork = true, silent = true }]
libreoffice_default = [{ command = "libreoffice", fork = true, silent = true }]

[extension]
gif.inherit = "image_default"
jpeg.inherit = "image_default"
jpg.inherit = "image_default"
png.inherit = "image_default"
webp.inherit = "image_default"
svg.inherit = "image_default"

flac.inherit = "audio_default"
m4a.inherit = "audio_default"
mp3.inherit = "audio_default"
wav.inherit = "audio_default"

avi.inherit = "video_default"
mp4.inherit = "video_default"
webm.inherit = "video_default"
wmv.inherit = "video_default"

build.inherit = "text_default"
c.inherit = "text_default"
cmake.inherit = "text_default"
conf.inherit = "text_default"
cpp.inherit = "text_default"
css.inherit = "text_default"
csv.inherit = "text_default"
env.inherit = "text_default"
go.inherit = "text_default"
h.inherit = "text_default"
html.inherit = "text_default"
ini.inherit = "text_default"
java.inherit = "text_default"
js.inherit = "text_default"
json.inherit = "text_default"
log.inherit = "text_default"
lua.inherit = "text_default"
md.inherit = "text_default"
py.inherit = "text_default"
sh.inherit = "text_default"
srt.inherit = "text_default"
toml.inherit = "text_default"
txt.inherit = "text_default"
xml.inherit = "text_default"
yaml.inherit = "text_default"
yml.inherit = "text_default"

odt.inherit = "libreoffice_default"
ods.inherit = "libreoffice_default"
odp.inherit = "libreoffice_default"
doc.inherit = "libreoffice_default"
docx.inherit = "libreoffice_default"
xls.inherit = "libreoffice_default"
xlsx.inherit = "libreoffice_default"
ppt.inherit = "libreoffice_default"
pptx.inherit = "libreoffice_default"

pdf.inherit = "reader_default"

torrent.inherit = "torrent_default"


7z.app_list = [
  { command = "7za", args = [
    "x",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

bz2.app_list = [
  { command = "tar", args = [
    "-xvjf",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

gz.app_list = [
  { command = "tar", args = [
    "-xvzf",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

tar.app_list = [
  { command = "tar", args = [
    "-xvf",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

tgz.app_list = [
  { command = "tar", args = [
    "-xvzf",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

rar.app_list = [
  { command = "unrar", args = [
    "x",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

xz.app_list = [
  { command = "tar", args = [
    "-xvJf",
  ], confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

zip.app_list = [
  { command = "unzip", confirm_exit = true },
  { command = "file-roller", fork = true, silent = true },
]

torrent.app_list = [{ command = "deluge", fork = true, silent = true }]

[mimetype.text]
inherit = "text_default"

[mimetype.video]
inherit = "video_default"

[mimetype.audio]
inherit = "audio_default"
