scroll_offset = 6
xdg_open = false
xdg_open_fork = false
use_trash = true
watch_files = true

[preview]
max_preview_size = 2097152
preview_script = "~/.local/bin/preview.sh"

[display]
show_hiden = true
mode = "default"
collapse_preview = true
column_ratio = [1, 3, 4]
show_borders = true
show_hidden = false
show_icons = true
tilde_in_titlebar = true
line_number_style = "none"

[display.sort]
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false
