---
- name: Remove packages
  apt:
    autoremove: true
    state: absent
    name: "{{ apt.remove }}"

- name: Add tailscale GPG apt key
  get_url:
    url: "{{ keyring.tailscale.url }}"
    dest: "{{ keyring.tailscale.dest }}"

- name: Add tailscale repo
  apt_repository:
    state: present
    repo: "deb [signed-by={{ keyring.tailscale.dest }}] https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

- name: Install packages with apt
  apt:
    update_cache: true
    state: present
    name: "{{ apt.install }}"

- name: Install .deb packages with apt
  apt:
    deb: "{{ item }}"
  with_items: "{{ apt.deb }}"
