- name: Get pCloud info
  import_tasks: ./pcloud.yaml

- name: Install binaries
  become_user: "{{ user }}"
  block:
    - name: Set list to iterate
      set_fact:
        binaries: "{{ bin + pcloud_bin }}"

    - name: Download bin archives
      get_url:
        url: "{{ item.url }}"
        dest: "{{ home }}/.local/bin/{{ item.name }}{{ '.' + item.extension if item.extension is defined else '' }}"
      with_items: "{{ binaries }}"

    - name: Unpack archives
      unarchive:
        remote_src: true
        src: "{{ home }}/.local/bin/{{ item.name }}.{{ item.extension }}"
        dest: "{{ home }}/.local/bin"
      with_items: "{{ binaries | selectattr('unpack', 'equalto', true) | list }}"

    - name: Delete compressed archives
      file:
        path: "{{ home }}/.local/bin/{{ item.name }}.{{ item.extension }}"
        state: absent
      with_items: "{{ binaries | selectattr('unpack', 'equalto', true) | list }}"

    - name: Set permission for bin files
      file:
        path: "{{ home }}/.local/bin/{{ item.name }}"
        mode: "0755"
        state: file
      with_items: "{{ binaries }}"
