- name: Get pCloud info
  import_tasks: ./pcloud.yaml

- name: Install binaries
  become_user: "{{ user }}"
  block:
    - name: Set list to iterate
      set_fact:
        binaries: "{{ bin + pcloud_bin }}"

    - name: Get binaries
      get_url:
        url: "{{ item.url }}"
        dest: "{{ home }}/.local/bin/{{ item.name }}"
      with_items: "{{ binaries | selectattr('unpack', 'equalto', false) | list }}"

    - name: Get archived binary files
      block:
        - name: Download archived binaries
          unarchive:
            list_files: true
            remote_src: true
            src: "{{ item.url }}"
            dest: "/tmp"
          with_items: "{{ binaries | selectattr('unpack', 'equalto', true) | list }}"
          register: archives

        - name: Rename the extracted binaries
          copy:
            src: "/tmp/{{ item.files[0] }}"
            dest: "{{ home }}/.local/bin/{{ item.item.name }}"
          with_items: "{{ archives.results }}"

    - name: Set permission for bin files
      file:
        path: "{{ home }}/.local/bin/{{ item.name }}"
        mode: "0755"
        state: file
      with_items: "{{ binaries }}"
