- name: Install binaries
  become_user: "{{ user }}"
  tags: [bin]
  block:
    - name: Get pCloud download link
      uri:
        url: "https://api.pcloud.com/getpublinkdownload?code={{ pcloud_code }}"
        return_content: true
      register: pcloud_response

    - name: Download bin archives
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.file }}"
      with_items:
        - url: "https://{{ pcloud_response['json']['hosts'][0] }}{{ pcloud_response['json']['path'] }}"
          file: "{{ home }}/.local/bin/pcloud"
        - url: "https://github.com/mgmeyers/pdfannots2json/releases/download/{{ pdfannots2json.version }}/pdfannots2json.{{ ansible_system }}.x{{ ansible_userspace_bits }}.tar.gz"
          file: /tmp/pdfannots2json.tar.gz
        - url: "https://github.com/hadolint/hadolint/releases/download/v{{ hadolint_version }}/hadolint-{{ ansible_system }}-{{ ansible_architecture }}"
          file: "{{ home }}/.local/bin/hadolint"

    - name: Extract pdfannots2json
      unarchive:
        src: /tmp/pdfannots2json.tar.gz
        remote_src: true
        dest: "{{ home }}/.local/bin"
        creates: "{{ home }}/.local/bin/pdfannots2json.tar.gz"

    - name: Set permission for bin files
      file:
        path: "{{ home }}/.local/bin/{{ item }}"
        mode: "0755"
        state: file
      with_items:
        - pcloud
        - pdfannots2json
        - hadolint
