---
- name: Install debugpy
  block:
    - name: Ensure ~/.virtualenvs directory exist
      ansible.builtin.file:
        path: "~/.virtualenvs"
        state: directory
        owner: "{{ user }}"
        mode: "0755"

    - name: Create debugpy virtualenv
      ansible.builtin.command:
        cmd: "python3 -m venv debugpy"
        chdir: "~/.virtualenvs"
        creates: "~/.virtualenvs/debugpy"

    - name: Install debugpy in virtualenv
      ansible.builtin.pip:
        extra_args: --upgrade
        virtualenv: "~/.virtualenvs/debugpy"
        state: present
        name: debugpy
