---
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Adding user to docker group
  user:
    name: phrmendes
    groups: docker,sudo
    append: yes
    state: present
