---
- name: Enable fingerprint support
  become: true
  when: ansible_form_factor != "Desktop"
  block:
    - name: Adding fingerprint repository
      ansible.builtin.apt_repository:
        repo: "ppa:uunicorn/open-fprintd"

    - name: Installing fingerprint packages
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - open-fprintd
          - fprintd-clients
          - python3-validity
