---
- name: Add the flathub remote repository
  community.general.flatpak_remote:
    flatpakrepo_url: "{{ flatpak.flathub }}"
    name: flathub
    state: present

- name: Install flatpak packages
  community.general.flatpak:
    state: present
    name: "{{ flatpak.install }}"
