---
- name: Add the flathub remote repository
  community.general.flatpak_remote:
    flatpakrepo_url: "{{ flatpak.flathub }}"
    method: user
    name: flathub
    state: present

- name: Install flatpak packages
  community.general.flatpak:
    state: present
    method: user
    name: "{{ flatpak.install }}"

- name: Give flatpak package permissions to read home directory
  become: true
  ansible.builtin.command: "flatpak override --filesystem=host {{ item }}"
  changed_when: false
  with_items: "{{ flatpak.install }}"
