---
- name: Add the flathub remote repository
  community.general.flatpak_remote:
    flatpakrepo_url: "{{ flatpak.flathub }}"
    name: flathub
    state: present

- name: Install flatpak packages
  community.general.flatpak:
    state: present
    name: "{{ flatpak.install }}"

- name: Give permissions to read home directory
  become: true
  ansible.builtin.command:
    cmd: "flatpak override --filesystem=home {{ item }}"
  changed_when: false
  with_items: "{{ flatpak.install }}"
