---
- name: Add the flathub remote repository
  become_user: "{{ user }}"
  community.general.flatpak_remote:
    flatpakrepo_url: "{{ flatpak.flathub }}"
    method: user
    name: flathub
    state: present

- name: Install packages with flatpak
  become_user: "{{ user }}"
  community.general.flatpak:
    state: present
    method: user
    name: "{{ flatpak.install }}"

- name: Give permissions to read home directory
  command:
    cmd: "flatpak override --filesystem=home {{ item }}"
  changed_when: false
  with_items: "{{ flatpak.install }}"
