--- 
- name: Check if home-manager is installed
  become_user: "{{ user }}"
  stat:
    path: "{{ nix.path.home_manager }}"
  register: home_manager

- name: Install home-manager
  become_user: "{{ user }}"
  block:
    - name: Create symlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - src: "{{ home }}/Projects/bkps/nix/config.nix"
          dest: "{{ home }}/.config/nixpkgs/config.nix"

    - name: Install
      command: "{{ nix.path.pkgs }} run nixpkgs#home-manager --switch --flake nix/#phrmendes"
      environment:
        NIXPKGS_ALLOW_UNFREE: "1"
  when: not home_manager.stat.exists
