---
- name: Download JetBrainsMono Nerd Font
  block:
    - name: Download font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
        dest: /tmp/jetbrainsmono.zip
        mode: "0755"

    - name: Ensure ~/.fonts exist
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        owner: "{{ user }}"
        mode: "0755"

    - name: Extract font
      ansible.builtin.unarchive:
        src: /tmp/jetbrainsmono.zip
        remote_src: true
        dest: ~/.fonts

    - name: Install font
      ansible.builtin.command:
        cmd: fc-cache -fv
        chdir: ~/.fonts
      changed_when: false
