---
- name: Check if /nix directory exists
  ansible.builtin.stat:
    path: /nix
  register: nix_directory

- name: Install nix
  become: true
  when: not nix_directory.stat.exists
  block:
    - name: Get installation script
      ansible.builtin.get_url:
        url: https://install.determinate.systems/nix
        dest: /tmp/nix_installer.sh
        mode: "0755"

    - name: Run installation script
      ansible.builtin.command:
        cmd: "./nix-installer.sh install --no-confirm"
        chdir: /tmp
        creates: /nix

- name: Run home-manager
  ansible.builtin.command: "nix run nixpkgs#home-manager --experimental-features 'nix-command flakes' -- switch --flake nix/#{{ user }}"
  environment:
    NIXPKGS_ALLOW_UNFREE: "1"
  changed_when: false
