---
- name: Check if nix package manager exists
  stat:
    path: "{{ nix.path.pkgs }}"
  register: nix_pkgs

- name: Install nix package manager
  block:
    - name: Download installer
      get_url:
        url: "{{ nix.installer.url }}"
        dest: /tmp
        checksum: "{{ nix.installer.checksum }}"

    - name: Extract installer
      unarchive:
        src: "/tmp/{{ nix.build }}.tar.xz"
        remote_src: true
        dest: /tmp

    - name: Run the installer
      become: true
      command:
        cmd: ./install --daemon </dev/null
        chdir: "/tmp/{{ nix.build }}"
  when: not nix_pkgs.stat.exists
