- name: Get pCloud zip file
  ansible.builtin.get_url:
    url: "https://api.pcloud.com/getpubzip?code={{ pcloud_code }}&filename=pcloud-{{ pcloud_version }}.zip"
    dest: /tmp/pcloud.zip
    mode: "0755"

- name: Unarchive pCloud zip file
  ansible.builtin.unarchive:
    src: /tmp/pcloud.zip
    remote_src: true
    dest: ~/.local/bin

- name: Set permission for pCloud binary
  ansible.builtin.file:
    path: ~/.local/bin/pcloud
    mode: "0755"
    state: file
