- name: Get pCloud download link
  ansible.builtin.uri:
    url: "https://api.pcloud.com/getpublinkdownload?code={{ pcloud_code }}"
    return_content: true
  register: pcloud_response

- name: Set pCloud url and name variables
  ansible.builtin.set_fact:
    pcloud_bin: "https://{{ pcloud_response['json']['hosts'][0] }}{{ pcloud_response['json']['path'] }}"

- name: Get pCloud binary
  ansible.builtin.get_url:
    url: "{{ pcloud_bin }}"
    dest: ~/.local/bin/pcloud
    mode: "0755"

- name: Set permission for pCloud binary
  ansible.builtin.file:
    path: ~/.local/bin/pcloud
    mode: "0755"
    state: file
