- name: Get pCloud download link
  uri:
    url: "https://api.pcloud.com/getpublinkdownload?code={{ pcloud_code }}"
    return_content: true
  register: pcloud_response

- name: Set pCloud url and name variables
  set_fact:
    pcloud_bin: "https://{{ pcloud_response['json']['hosts'][0] }}{{ pcloud_response['json']['path'] }}"

- name: Get binary
  get_url:
    url: "{{ pcloud_bin }}"
    dest: "{{ home }}/.local/bin/pcloud"

- name: Set permission for bin files
  file:
    path: "{{ home }}/.local/bin/pcloud"
    mode: "0755"
    state: file
