- name: Get pCloud download link
  uri:
    url: "https://api.pcloud.com/getpublinkdownload?code={{ pcloud_code }}"
    return_content: true
  register: pcloud_response

- name: Set pCloud url and name variables
  set_fact:
    pcloud_bin:
      - url: "https://{{ pcloud_response['json']['hosts'][0] }}{{ pcloud_response['json']['path'] }}"
        name: pcloud
        unpack: false
