---
- name: Config python via pyenv
  become_user: "{{ user }}"
  block:
    - name: Check all available python versions
      command: "pyenv versions"
      register: all_python_versions
      changed_when: false

    - name: Check active python version
      shell: "pyenv version | cut -d ' ' -f 1"
      register: active_python_version
      changed_when: false

    - name: Install python
      command: "pyenv install {{ python.version }}"
      when: python.version not in all_python_versions.stdout

    - name: Set python global version
      command: "pyenv global {{ python.version }}"
      when: python.version != active_python_version.stdout

    - name: Get pip bin
      command: "pyenv which pip"
      register: pip_bin
      changed_when: false

    - name: Install python packages
      pip:
        executable: "{{ pip_bin.stdout }}"
        name: "{{ python.install }}"

    - name: Configure poetry to use virtualenvs inside projects
      command:
        cmd: "pyenv exec poetry config virtualenvs.in-project true"
      changed_when: false
