---
- name: Config python via pyenv
  become_user: "{{ user }}"
  block:
    - name: Check python version 
      shell: "pyenv versions"
      register: pyenv_versions
      changed_when: false

    - name: Install python
      command: "pyenv install {{ python.version }}"
      when: python.version not in pyenv_versions.stdout

    - name: Set python global version
      command: "pyenv global {{ python.version }}"
      when: python.version != pyenv_versions.stdout

    - name: Get pip bin
      command: "pyenv which pip"
      register: pip_bin
      changed_when: false

    - name: Install python packages
      pip:
        executable: "{{ pip_bin.stdout }}"
        name: "{{ python.install }}"

    - name: Configure poetry to use virtualenvs inside projects
      command:
        cmd: "pyenv exec poetry config virtualenvs.in-project true"
      changed_when: false

    - name: Install python debugger
      pip:
        name: debugpy
        virtualenv: "/home/{{ user }}/.virtualenvs/debugpy"
