---
- name: Set tailscale keyring
  set_fact:
    tailscale_keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Add tailscale GPG apt key
  get_url:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg
    dest: "{{ tailscale_keyring }}"

- name: Add tailscale repo
  apt_repository:
    state: present
    repo: "deb [signed-by={{ tailscale_keyring }}] https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
