---
ansible_arch_alias: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
ansible_dist_alias: "{{ 'Ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution }}"

user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - io.podman_desktop.PodmanDesktop
    - org.wezfurlong.wezterm

apt:
  remove:
    - baobab
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - font-jetbrains-mono
    - gnome-tweaks
    - nala
    - openssh-server
    - podman
    - podman-docker
    - podman-toolbox
    - seahorse-nautilus
    - v4l2loopback-dkms
    - v4l2loopback-utils
