---
user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
home_prefix: "{{ '/home' if ansible_system == 'Linux' else '/Users'}}"
home: "{{ home_prefix }}/{{ user }}"
docker_users: ["{{ user }}"]

bruno_version: 0.22.0
hadolint_version: 2.12.0
mathpix_version: 03.00.0104
nix_version: 2.17.0
pcloud_code: XZpL8AVZAqfCXz5TebJ2gcvAiHi15pYFKPey
pdfannots2json_version: 1.0.16
tailscale_keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - com.bitwarden.desktop
    - com.github.tchx84.Flatseal
    - com.uploadedlobster.peek
    - de.haeckerfelix.Fragments
    - info.febvre.Komikku
    - io.github.celluloid_player.Celluloid
    - md.obsidian.Obsidian
    - org.libreoffice.LibreOffice
    - org.wezfurlong.wezterm
    - org.zotero.Zotero

bin:
  - url: "https://github.com/mgmeyers/pdfannots2json/releases/download/{{ pdfannots2json_version }}/pdfannots2json.{{ ansible_system }}.x{{ ansible_userspace_bits }}.tar.gz"
    name: pdfannots2json
    unpack: true
    extension: tar.gz
  - url: "https://download.mathpix.com/{{ ansible_system | lower }}/Mathpix_Snipping_Tool-{{ ansible_architecture }}.v{{ mathpix_version }}.AppImage"
    name: mathpix
    unpack: false

apt:
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - build-essential
    - ca-certificates
    - chromium-browser
    - chromium-chromedriver
    - code
    - curl
    - file
    - file-roller
    - flatpak
    - fonts-jetbrains-mono
    - gnome-tweaks
    - gnupg
    - gparted
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - mlocate
    - nala
    - openssh-server
    - rar
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xz-utils
    - zip
    - zlib1g-dev
