---
ansible_arch_alias: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
ansible_dist_alias: "{{ 'Ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution }}"

user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

nix_version: 2.18.0

quarto_version: 1.3.450
quarto_base_url: "https://github.com/quarto-dev/quarto-cli/releases/download"

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - ch.protonmail.protonmail-bridge
    - com.bitwarden.desktop
    - com.github.ahrm.sioyek
    - com.github.hluk.copyq
    - com.hunterwittenborn.Celeste
    - com.protonvpn.www
    - com.uploadedlobster.peek
    - de.haeckerfelix.Fragments
    - io.dbeaver.DBeaverCommunity
    - io.podman_desktop.PodmanDesktop
    - md.obsidian.Obsidian
    - org.flameshot.Flameshot
    - org.gnome.Boxes
    - org.libreoffice.LibreOffice
    - org.videolan.VLC
    - org.wezfurlong.wezterm

apt:
  deb:
    - "{{ quarto_base_url }}/v{{ quarto_version }}/quarto-{{ quarto_version }}-{{ ansible_system | lower }}-{{ ansible_arch_alias }}.deb"
    - "{{ wezterm_base_url }}/{{ wezterm_version }}/wezterm-{{ wezterm_version }}.{{ ansible_dist_alias }}{{ ansible_distribution_version }}.deb"
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - autoconf
    - automake
    - binutils
    - bison
    - build-essential
    - ca-certificates
    - chromium-browser
    - chromium-chromedriver
    - curl
    - file
    - file-roller
    - flatpak
    - fonts-jetbrains-mono
    - g++
    - gcc
    - gnome-tweaks
    - gnupg
    - gparted
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libxml2-dev
    - libxmlsec1-dev
    - make
    - mlocate
    - nala
    - openssh-server
    - patch
    - pkg-config
    - podman
    - podman-docker
    - podman-toolbox
    - python3-apt
    - python3-openssl
    - python3-pip
    - python3-pycurl
    - python3-setuptools
    - rar
    - seahorse-nautilus
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xclip
    - xz-utils
    - zip
    - zlib1g-dev
