---
ansible_arch_alias: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
home_prefix: "{{ '/home' if ansible_system == 'Linux' else '/Users'}}"
home: "{{ home_prefix }}/{{ user }}"

bruno_version: 0.24.0
hadolint_version: 2.12.0
neovide_version: 0.11.2
nix_version: 2.17.0

pcloud_code: XZpL8AVZAqfCXz5TebJ2gcvAiHi15pYFKPey
tailscale_keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - org.wezfurlong.wezterm

bin:
  - url: "https://github.com/usebruno/bruno/releases/download/v{{ bruno_version }}/bruno_{{ bruno_version }}_{{ ansible_architecture }}_{{ ansible_system | lower }}.AppImage"
    name: bruno
    unpack: false
  - url: "https://github.com/hadolint/hadolint/releases/download/v{{ hadolint_version }}/hadolint-{{ ansible_system }}-{{ ansible_architecture }}"
    name: hadolint
    unpack: false
  - url: "https://github.com/neovide/neovide/releases/download/{{ neovide_version }}/neovide.AppImage"
    name: neovide
    unpack: false

desktop_entries:
  - name: Bruno
    icon: https://raw.githubusercontent.com/usebruno/bruno/main/assets/images/logo-transparent.png
    icon_size: 512x512
    comment: Open source API client
    terminal: "false"
    single_window: "false"

apt:
  deb:
    - "https://github.com/quarto-dev/quarto-cli/releases/download/v{{ quarto_version }}/quarto-{{ quarto_version }}-{{ ansible_system | lower }}-{{ ansible_arch_alias }}.deb"
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - build-essential
    - ca-certificates
    - chromium-browser
    - chromium-chromedriver
    - curl
    - file
    - file-roller
    - flatpak
    - fonts-jetbrains-mono
    - gnome-tweaks
    - gnupg
    - gparted
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - mlocate
    - nala
    - openssh-server
    - rar
    - seahorse-nautilus
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xz-utils
    - zip
    - zlib1g-dev
