---
ansible_arch_alias: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
home_prefix: "{{ '/home' if ansible_system == 'Linux' else '/Users'}}"
home: "{{ home_prefix }}/{{ user }}"

nix_version: 2.17.0
quarto_version: 1.3.450

pcloud_code: XZ5iuiVZQsuexQaMmmLAS7FGWNh1TkXRWJR7

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - ch.protonmail.protonmail-bridge
    - com.protonvpn.www
    - org.wezfurlong.wezterm

apt:
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - build-essential
    - ca-certificates
    - chromium-browser
    - chromium-chromedriver
    - curl
    - file
    - file-roller
    - flatpak
    - fonts-jetbrains-mono
    - gnome-tweaks
    - gnupg
    - gparted
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - mlocate
    - nala
    - openssh-server
    - rar
    - seahorse-nautilus
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xz-utils
    - zip
    - zlib1g-dev
