---
ansible_arch_alias: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
ansible_dist_alias: "{{ 'Ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution }}"

user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

nix_version: 2.18.0

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - ch.protonmail.protonmail-bridge
    - com.bitwarden.desktop
    - com.github.hluk.copyq
    - com.protonvpn.www
    - com.uploadedlobster.peek
    - de.haeckerfelix.Fragments
    - io.dbeaver.DBeaverCommunity
    - io.podman_desktop.PodmanDesktop
    - md.obsidian.Obsidian
    - org.gnome.Boxes
    - org.libreoffice.LibreOffice
    - org.mozilla.Thunderbird
    - org.videolan.VLC
    - org.wezfurlong.wezterm
    - org.zotero.Zotero

apt:
  remove:
    - baobab
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - chromium-browser
    - chromium-chromedriver
    - file-roller
    - gnome-tweaks
    - gnupg
    - gparted
    - nala
    - openssh-server
    - podman
    - podman-docker
    - podman-toolbox
    - seahorse-nautilus
    - tailscale
    - unzip
    - v4l2loopback-dkms
    - v4l2loopback-utils
    - zip
