---
user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
home_prefix: "{{ '/home' if ansible_system == 'Linux' else '/Users'}}"
home: "{{ home_prefix }}/{{ user }}"
docker_users: ["{{ user }}"]
pcloud_code: XZpL8AVZAqfCXz5TebJ2gcvAiHi15pYFKPey
hadolint_version: 2.12.0
nix_version: 2.17.0
obsidian_version: 1.4.14
pdfannots2json_version: 1.0.16
bruno_version: 0.22.0
keyring:
  tailscale:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - com.uploadedlobster.peek
    - com.zettlr.Zettlr
    - org.wezfurlong.wezterm
apt:
  deb:
    - "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.14/obsidian_{{ obsidian_version }}_{{ ansible_arch_alias }}.deb"
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - gparted
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - build-essential
    - ca-certificates
    - curl
    - file
    - file-roller
    - flatpak
    - fonts-jetbrains-mono
    - gnome-tweaks
    - gnupg
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - mlocate
    - nala
    - openssh-server
    - rar
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xz-utils
    - zip
    - zlib1g-dev
