---
ansible_distribution: "{{ 'Ubuntu' if ansible_distribution == 'Pop!_OS' else ansible_distribution }}"
ansible_arch_alias: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
home_prefix: "{{ '/home' if ansible_system == 'Linux' else '/Users'}}"
home: "{{ home_prefix }}/{{ user }}"
docker_users: ["{{ user }}"]

bruno_version: 0.22.0
hadolint_version: 2.12.0
mathpix_version: 03.00.0104
nix_version: 2.17.0
pdfannots2json_version: 1.0.16
quarto_version: 1.3.450

pcloud_code: XZpL8AVZAqfCXz5TebJ2gcvAiHi15pYFKPey
tailscale_keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - io.github.celluloid_player.Celluloid
    - org.wezfurlong.wezterm
    - net.cozic.joplin_desktop

bin:
  - url: "https://github.com/mgmeyers/pdfannots2json/releases/download/{{ pdfannots2json_version }}/pdfannots2json.{{ ansible_system }}.x{{ ansible_userspace_bits }}.tar.gz"
    name: pdfannots2json
    unpack: true
    extension: tar.gz
  - url: "https://download.mathpix.com/{{ ansible_system | lower }}/Mathpix_Snipping_Tool-{{ ansible_architecture }}.v{{ mathpix_version }}.AppImage"
    name: mathpix
    unpack: false
  - url: "https://github.com/usebruno/bruno/releases/download/v{{ bruno_version }}/bruno_{{ bruno_version }}_{{ ansible_architecture }}_{{ ansible_system | lower }}.AppImage"
    name: bruno
    unpack: false
  - url: "https://github.com/hadolint/hadolint/releases/download/v{{ hadolint_version }}/hadolint-{{ ansible_system }}-{{ ansible_architecture }}"
    name: hadolint
    unpack: false

apt:
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - build-essential
    - ca-certificates
    - chromium-browser
    - chromium-chromedriver
    - code
    - curl
    - file
    - file-roller
    - flatpak
    - fonts-jetbrains-mono
    - gnome-tweaks
    - gnupg
    - gparted
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - mlocate
    - nala
    - openssh-server
    - rar
    - seahorse-nautilus
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xz-utils
    - zip
    - zlib1g-dev
  deb:
    - "https://code.visualstudio.com/sha/download?build=stable&os={{ ansible_system }}-deb-x{{ ansible_userspace_bits }}"
    - https://github.com/quarto-dev/quarto-cli/releases/download/v{{ quarto_version }}/quarto-{{ quarto_version }}-{{  }}-amd64.deb
