---
user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
home_prefix: "{{ '/home' if ansible_system == 'Linux' else '/Users'}}"
home: "{{ home_prefix }}/{{ user }}"
docker_users: ["{{ user }}"]
pcloud:
  code: XZecm6VZIz4VKYBrUbzzhcfNW9boSfrfhgaV
  version: 1.14.0
nix:
  version: 2.17.0
python:
  version: 3.11.5
  install:
    - ansible
    - ipykernel
    - ipython
    - poetry
keyring:
  tailscale:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
flatpak:
  flathub: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - com.uploadedlobster.peek
    - com.zettlr.Zettlr
    - md.obsidian.Obsidian
    - org.wezfurlong.wezterm
apt:
  remove:
    - baobab
    - evince
    - fprintd
    - geary
    - gedit
    - gnome-calendar
    - gnome-contacts
    - gparted
    - libreoffice-common
    - libreoffice-core
    - simple-scan
    - totem
  install:
    - 7zip
    - build-essential
    - ca-certificates
    - file
    - file-roller
    - flatpak
    - fonts-dejavu
    - fonts-jetbrains-mono
    - gnome-tweaks
    - gnupg
    - gzip
    - libbz2-dev
    - libffi-dev
    - libfuse2
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - mlocate
    - nala
    - openssh-server
    - python3-poppler-qt5
    - python3-pyqt5
    - python3-yaml
    - rar
    - tailscale
    - tk-dev
    - uidmap
    - unrar
    - unzip
    - v4l2loopback-utils
    - wget
    - xz-utils
    - zip
    - zlib1g-dev
