# mod keys
mod1:
  - option
mod2:
  - option
  - shift

# layouts
enables-layout-hud: true
layouts:
  - bsp
  - fullscreen
  - column

# windows
window-margins: true
window-margin-size: 10
float-small-windows: true
follow-space-thrown-windows: false

# padding
screen-padding-left: 3
screen-padding-bottom: 3
screen-padding-right: 3
screen-padding-top: 3

# mouse
mouse-follows-focus: false
focus-follows-mouse: false
mouse-resizes-windows: true

# keys
relaunch-amethyst:
  mod: mod2
  key: z
cycle-layout:
  mod: mod1
  key: y
focus-cw:
  mod: mod1
  key: j
focus-ccw:
  mod: mod1
  key: k
shrink-main:
  mod: mod1
  key: h
expand-main:
  mod: mod1
  key: l
focus-main:
  mod: mod1
  key: enter
swap-cw:
  mod: mod2
  key: h
swap-ccw:
  mod: mod2
  key: l
toggle-float:
  mod: mod1
  key: f

