# mod keys
mod1:
  - command
mod2:
  - command
  - shift

# layouts
enables-layout-hud: true
layouts:
  - bsp
  - fullscreen
  - column

# windows
window-margins: true
window-margin-size: 10
float-small-windows: true
follow-space-thrown-windows: false

# padding
screen-padding-left: 3
screen-padding-bottom: 3
screen-padding-right: 3
screen-padding-top: 3

# mouse
mouse-follows-focus: false
focus-follows-mouse: false
mouse-resizes-windows: true

# keys
cycle-layout:
  mod: mod1
  key: \
shrink-main:
  mod: mod2
  key: h
expand-main:
  mod: mod2
  key: l
focus-cw:
  mod: mod1
  key: j
focus-ccw:
  mod: mod1
  key: k
relaunch-amethyst:
  mod: mod2
  key: x
toggle-tiling:
  mod: mod2
  key: d
