# mod keys
mod1:
  - option
mod2:
  - option
  - shift

# layouts
enables-layout-hud: true
layouts:
  - tall
  - bsp
  - fullscreen

# windows
window-margins: true
window-margin-size: 10
float-small-windows: true
follow-space-thrown-windows: false

# padding
screen-padding-left: 3
screen-padding-bottom: 3
screen-padding-right: 3
screen-padding-top: 3

# mouse
mouse-follows-focus: false
focus-follows-mouse: false
mouse-resizes-windows: true

# keys
reevaluate-windows:
  mod: mod1
  key: z
relaunch-amethyst:
  mod: mod2
  key: z
cycle-layout:
  mod: mod2
  key: space
focus-cw:
  mod: mod1
  key: up
focus-ccw:
  mod: mod1
  key: down
shrink-main:
  mod: mod2
  key: s
expand-main:
  mod: mod2
  key: e
swap-cw:
  mod: mod2
  key: h
swap-ccw:
  mod: mod2
  key: l
toggle-float:
  mod: mod2
  key: f
throw-space-right:
  mod: mod2
  key: right
throw-space-left:
  mod: mod2
  key: left
throw-screen-1:
  mod: mod2
  key: 1
throw-screen-2:
  mod: mod2
  key: 2
throw-screen-3:
  mod: mod2
  key: 3
throw-screen-4:
  mod: mod2
  key: 4
throw-screen-5:
  mod: mod2
  key: 5
